/* ═══════════════════════════════════════════════════════════════════════════
   SWITCH DIAGNOSTIC TOOL — app.js
   Current Engineering
   ═══════════════════════════════════════════════════════════════════════════

   TABLE OF CONTENTS
   ─────────────────
   1.  DTC LIBRARY              ← ADD NEW DTC CODES HERE
   2.  NEWSLETTER DATA          ← ADD NEW NEWSLETTER ISSUES HERE
   3.  Application State
   4.  Clock
   5.  Vehicle Selection
   6.  Sidebar
   7.  Case Progress Bar
   8.  Problem Statement Form
   9.  Case Rendering
   10. Answer Logic (setAns, saveNotes)
   11. Case Navigation
   12. Finish / Summary Screen
   13. Export (PDF, Word)
   14. Page Navigation
   15. Newsletter (render, reader, subscribe)

═══════════════════════════════════════════════════════════════════════════ */


/* ══════════════════════════════════════════════════════════════════════════
   1. DTC LIBRARY
   ══════════════════════════════════════════════════════════════════════════

   HOW TO ADD A NEW DTC (e.g. DTC 7)
   ──────────────────────────────────
   1. Parse your Excel file using:  scripts/parse_excel.py  (see scripts folder)
   2. It will print a JSON array — copy it
   3. Add a new key below:

      "7": {
        code: "7",
        name: "YourFaultName",
        description: "Full description of the fault",
        action: "Immediate action e.g. Shutdown the System",
        severity: "CRITICAL",    // CRITICAL | HIGH | MEDIUM
        category: "HV Battery",  // Your category label
        vehicles: ["BUS","LCV"], // Which vehicles this DTC applies to
        cases: [ ...paste JSON array from parse_excel.py here... ]
      }

   CASE OBJECT STRUCTURE (each Excel sheet = one case)
   ─────────────────────────────────────────────────────
   {
     sheet:       "Case1",                   // Sheet name from Excel
     area_group:  "Junction Box to Sub Pack", // Col E first part (before :)
     area_detail: "Wire continuity check",    // Col E second part (after :)
     steps: [
       {
         step:        "Check for continuity...",   // Col F (Step)
         obs_label:   "Continuity Yes or No",      // Col G (Observation label)
         corrective:  "If not observed...",         // Col H (Corrective Action)
         input_type:  "yesno"  // "yesno" | "condition" | "number"
       }
     ]
   }

   INPUT TYPE GUIDE
   ─────────────────
   "yesno"     → YES / NO buttons  (use for continuity checks)
   "condition" → OK / NOT OK buttons (use for mounting/visual checks)
   "number"    → numeric text field (use for resistance/voltage readings)
                 The script auto-detects input_type from the Observation column.
══════════════════════════════════════════════════════════════════════════ */

const DTC_LIBRARY = {

  "4": {
    code:        "4",
    name:        "HighVltgBattFault",
    description: "High Voltage Battery pack fault",
    action:      "Shutdown the System",
    severity:    "CRITICAL",
    category:    "HV Battery",
    vehicles:    ["BUS", "LCV"],

    /* cases array — generated by scripts/parse_excel.py from error_code_4.xlsx */
    cases: DTC_4_CASES   /* ← this variable is injected by index.html from data/dtc_4_cases.js */
  },
  "69": {
    code:        "69",
    name:        "Acc Pedal Supply fault",
    description: "Accelerator pedal power supply fault",
    action:      "Creep",
    severity:    "CRITICAL",
    category:    "Sensor",
    vehicles:    ["BUS", "LCV"],

    /* cases array — generated by scripts/parse_excel.py from error_code_4.xlsx */
    cases: DTC_69_CASES   /* ← this variable is injected by index.html from data/dtc_4_cases.js */
  },
  "13": {
  code:        "13",
  name:        "TrctInvrtrCanMssing",
  description: "Traction inverter CAN messages missing",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "Inverter",
  vehicles:    ["BUS", "LCV"],

  /* cases array — generated by scripts/parse_excel.py from error_code_13.xlsx */
  cases: DTC_13_CASES   /* ← this variable is injected by index.html from data/dtc_13_cases.js */
  },

  "55": {
  code:        "55",
  name:        "EmstopSwthWhilStrtg",
  description: "Emergency stop button detected as pressed while starting",
  action:      "Shutdown the System & Disable Charging",
  severity:    "CRITICAL",
  category:    "Safety",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_55_CASES
  },

  "62": {
  code:        "62",
  name:        "TrctInvrtrStateDisgree",
  description: "Commanded and actual traction inverter states disagree",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "Inverter",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_62_CASES
  },

  "74": {
  code:        "74",
  name:        "FnrFault",
  description: "Fault in FNR CAN message",
  action:      "ShutdownWhenStatnry",
  severity:    "HIGH",
  category:    "Transmission",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_74_CASES
  },

  "88": {
  code:        "88",
  name:        "AuxWhCnctactOpenIncrrct",
  description: "Auxiliary HV contactors are open when they should be closed",
  action:      "Shutdown the System & Disable Charging",
  severity:    "CRITICAL",
  category:    "Auxiliary",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_88_CASES
  },

  "98": {
  code:        "98",
  name:        "BrakePedlTracksDisgree",
  description: "Brake pedal tracks disagree while starting",
  action:      "Creep",
  severity:    "HIGH",
  category:    "Brake",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_98_CASES
  },
  
  "100": {
  code:        "100",
  name:        "CooltTempSensorPwrsuPoleault",
  description: "Coolant temperature sensor power supply fault",
  action:      "Warning",
  severity:    "MEDIUM",
  category:    "Sensor",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_100_CASES
  },

  "101": {
  code:        "101",
  name:        "CanAOffWhilRnng",
  description: "CAN_A missing while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "CAN",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_101_CASES
  },

  "103": {
  code:        "103",
  name:        "CanBOffWhilRnng",
  description: "CAN_B missing while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "CAN",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_103_CASES
  },
   "140": {
  code:        "140",
  name:        "AuxInvrtr2CanFaultWhilStrtg",
  description: "Aux Inverter 2 (EPAS) CAN Fault while starting",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "Auxiliary",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_140_CASES
  },

   "145": {
  code:        "145",
  name:        "AuxInvrtr1CanFaultWhilStrtg",
  description: "Aux Inverter 1 (EPAS) CAN Fault while starting",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "Auxiliary",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_145_CASES
  },

  "146": {
  code:        "146",
  name:        "BcuCanFaultWhilRnng",
  description: "BCU CAN Fault while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "CAN",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_146_CASES
  },

  "152": {
  code:        "152",
  name:        "BcuCanFaultWhilRning",
  description: "BCU CAN Fault while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "CAN",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_152_CASES
  },
  
  "155": {
  code:        "155",
  name:        "Dcdc1CanFaultWhilRnng",
  description: "DC/DC 1 CAN Fault while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "DC/DC",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_155_CASES
  },
  "101": {
  code:        "101",
  name:        "CanACOffWhilRnng",
  description: "CAN_A missing while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "CAN",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_101_CASES
  },
    "102": {
  code:        "102",
  name:        "CanBOffWhilRnng",
  description: "CAN_B missing while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "CAN",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_102_CASES
  },
    "103": {
  code:        "103",
  name:        "CanCOffWhilRnng",
  description: "CAN_C missing while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "CAN",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_103_CASES
  },

  "104": {
  code:        "104",
  name:        "CanDOff",
  description: "CAN_D missing",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "CAN",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_104_CASES
  },

  "108": {
  code:        "108",
  name:        "AuxInvrtr1FaultWhilRnng",
  description: "Auxiliary inverter 1 fault while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "Auxiliary",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_108_CASES
  },

  "109": {
  code:        "109",
  name:        "AuxInvrtr2FaultWhilRnng",
  description: "Auxiliary inverter 2 fault while running",
  action:      "Shutdown the System",
  severity:    "CRITICAL",
  category:    "Auxiliary",
  vehicles:    ["BUS", "LCV"],
  cases:       DTC_109_CASES
  }
  /* ─── ADD MORE DTC ENTRIES ABOVE THIS LINE ─── */

};


/* ══════════════════════════════════════════════════════════════════════════
   2. NEWSLETTER DATA
   ══════════════════════════════════════════════════════════════════════════

   HOW TO ADD A NEW ISSUE
   ──────────────────────
   Paste a new object at the TOP of this array (index 0 = featured article).

   FIELDS
   ──────
   id          → issue number (integer)
   date        → display date string e.g. "March 25, 2026"
   readTime    → e.g. "5 min"
   isNew       → true/false — shows NEW badge on card
   title       → headline
   tags        → array of tag strings
   tagColors   → array matching tags: "pu" | "gr" | "bl"
   excerpt     → short preview (shown on card)
   sections    → array of { heading: "...", body: "..." }
                 Use \n in body for line breaks.
══════════════════════════════════════════════════════════════════════════ */

const NL_DATA = [
  {
    id: 1, date: "April, 2026", readTime: "3 min", isNew: false,
    title: "How to use the Telematics Data Merger and Paramters segregator app",
    tags: ["PDF"],
    tagColors: ["pu", "gr", "bl"],
    excerpt: "The App mergers the Telematics data and give required parametrs",
    sections: [
      {
        heading: "Data merger",
        body: "Section 1 — Problem Discription: Merges Data for a commom VIN number.\n\nSection 2 — Inputs: Upload the files with common VIN Number.\n\nSection 3 — Select required Parameters:: Tick the Required paramters."
      }
    ]
  }

  /* ─── ADD NEW NEWSLETTER ISSUES ABOVE THIS LINE ─── */
];


/* ══════════════════════════════════════════════════════════════════════════
   3. APPLICATION STATE
   ══════════════════════════════════════════════════════════════════════════ */

const SESS = 'SW-' + Date.now().toString(36).toUpperCase().slice(-6);

let vehicle    = null;   // "BUS" or "LCV"
let activeDTC  = null;   // reference to a DTC_LIBRARY entry
let activeDTC2 = null;
let currentCase = 0;     // index into activeDTC.cases[]
let answers    = {};     // answers[caseIdx][stepIdx] = { value, notes }
let intake     = {};     // problem statement form data


/* ══════════════════════════════════════════════════════════════════════════
   4. CLOCK
══════════════════════════════════════════════════════════════════════════ */

function tick() {
  document.getElementById('clock').textContent =
    new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false });
}
setInterval(tick, 1000);
tick();


/* ══════════════════════════════════════════════════════════════════════════
   5. VEHICLE SELECTION
══════════════════════════════════════════════════════════════════════════ */

function selectVehicle(v) {
  vehicle = v;
  document.getElementById('veh-overlay').classList.add('hidden');
  document.getElementById('vBadge').textContent = v + ' ▾';
  document.getElementById('vLbl').textContent   = v;
  buildSidebar();
  showProblemStatement();
}

function switchVehicle() {
  document.getElementById('veh-overlay').classList.remove('hidden');
}


/* ══════════════════════════════════════════════════════════════════════════
   6. SIDEBAR
══════════════════════════════════════════════════════════════════════════ */

function buildSidebar() {
  const list  = document.getElementById('dtcList');
  list.innerHTML = '';

  /* Filter DTC codes for the selected vehicle */
  const codes = Object.values(DTC_LIBRARY).filter(
    d => !d.vehicles || d.vehicles.includes(vehicle)
  );

  document.getElementById('dtcCnt').textContent  = codes.length;
  document.getElementById('sessDisp').textContent = SESS;

  codes.forEach(d => {
    const el = document.createElement('div');
    el.className = 'dtc-card';
    el.innerHTML = `
      <div class="dc-n">DTC ${d.code} · ${d.cases.length} cases</div>
      <div class="dc-t">${d.name}</div>
      <div class="dc-d">${d.description}</div>`;
    el.onclick = () => { activeDTC = d; currentCase = 0; answers = {}; renderCase(0); };
    list.appendChild(el);
  });
}

function buildSidebar() {
  const list  = document.getElementById('dtcList');
  list.innerHTML = '';

  /* Filter DTC codes for the selected vehicle */
  const codes = Object.values(DTC_LIBRARY).filter(
    d => !d.vehicles || d.vehicles.includes(vehicle)
  );

  document.getElementById('dtcCnt').textContent  = codes.length;
  document.getElementById('sessDisp').textContent = SESS;

  codes.forEach(d => {
    const el = document.createElement('div');
    el.className = 'dtc-card';
    el.innerHTML = `
      <div class="dc-n">DTC2 ${d.code} · ${d.cases.length} cases</div>
      <div class="dc-t">${d.name}</div>
      <div class="dc-d">${d.description}</div>`;
    el.onclick = () => { activeDTC2 = d; currentCase = 0; answers = {}; renderCase(0); };
    list.appendChild(el);
  });
}
/* ══════════════════════════════════════════════════════════════════════════
   7. CASE PROGRESS BAR
   Builds numbered circles for each case, updates colour as user progresses.
══════════════════════════════════════════════════════════════════════════ */

function buildCaseBar(dtc) {
  const bar = document.getElementById('caseBar');
  bar.innerHTML = '';

  dtc.cases.forEach((c, i) => {
    if (i > 0) {
      const sep = document.createElement('div');
      sep.className = 'cs-sep';
      sep.id = 'csep' + i;
      bar.appendChild(sep);
    }
    const s = document.createElement('div');
    s.className = 'cs';
    s.id = 'cst' + i;
    s.innerHTML = `<div class="cs-n" title="${c.area_detail}">${i + 1}</div><span class="cs-l">${c.area_detail || c.sheet}</span>`;
    s.onclick = () => { if (i <= currentCase || answers[i]) navigateCase(i); };
    bar.appendChild(s);
  });
  updateCaseBar(0);
}

function updateCaseBar(active) {
  if (!activeDTC) return;
  activeDTC.cases.forEach((_, i) => {
    const el  = document.getElementById('cst' + i);
    if (!el) return;
    el.classList.remove('active', 'done');
    if (i < active)      el.classList.add('done');
    else if (i === active) el.classList.add('active');

    const sep = document.getElementById('csep' + i);
    if (sep) sep.style.background = i <= active ? 'var(--green)' : 'var(--border)';
  });

  const total = activeDTC.cases.length;
  document.getElementById('d-prog').textContent =
    active >= total ? 'Complete' : `Case ${active + 1} of ${total}`;
}

function buildCaseBar(dtc) {
  const bar = document.getElementById('caseBar');
  bar.innerHTML = '';

  dtc.cases.forEach((c, i) => {
    if (i > 0) {
      const sep = document.createElement('div');
      sep.className = 'cs-sep';
      sep.id = 'csep' + i;
      bar.appendChild(sep);
    }
    const s = document.createElement('div');
    s.className = 'cs';
    s.id = 'cst' + i;
    s.innerHTML = `<div class="cs-n" title="${c.area_detail}">${i + 1}</div><span class="cs-l">${c.area_detail || c.sheet}</span>`;
    s.onclick = () => { if (i <= currentCase || answers[i]) navigateCase(i); };
    bar.appendChild(s);
  });
  updateCaseBar(0);
}

function updateCaseBar(active) {
  if (!activeDTC2) return;
  activeDTC2.cases.forEach((_, i) => {
    const el  = document.getElementById('cst' + i);
    if (!el) return;
    el.classList.remove('active', 'done');
    if (i < active)      el.classList.add('done');
    else if (i === active) el.classList.add('active');

    const sep = document.getElementById('csep' + i);
    if (sep) sep.style.background = i <= active ? 'var(--green)' : 'var(--border)';
  });

  const total = activeDTC2.cases.length;
  document.getElementById('d-prog').textContent =
    active >= total ? 'Complete' : `Case ${active + 1} of ${total}`;
}

/* ══════════════════════════════════════════════════════════════════════════
   8. PROBLEM STATEMENT FORM
   Shown before diagnostics start. Maps directly to the report template.
══════════════════════════════════════════════════════════════════════════ */

function showProblemStatement() {
  document.getElementById('caseBar').innerHTML  = '';
  document.getElementById('dOp').textContent    = 'Problem Statement';
  document.getElementById('d-prog').textContent = '';

  const dtcOpts = Object.values(DTC_LIBRARY)
    .filter(d => !d.vehicles || d.vehicles.includes(vehicle))
    .map(d => `<option value="${d.code}">DTC ${d.code} — ${d.name}</option>`)
    .join('');

  document.getElementById('diagContent').innerHTML = `
    <div style="max-width:720px;margin:20px auto;">
      <div class="ps-form">
        <img src="assets/logo.jpg" class="ps-logo" alt="SWITCH">
        <div class="ps-title">New Diagnostic Report</div>
        <div class="ps-sub">Fill in the problem statement before starting. All fields appear in the exported report.</div>

        <!-- SECTION 1: Problem Discription -->
        <div class="ps-section">
          <div class="sec-heading">Problem Discription</div>
          <div class="form-grid" style="grid-template-columns:1fr">
            <div class="frow">
              <label class="flabel">Problem Discription / Background *</label>
              <textarea class="finput" id="fi-intro" rows="4"
                placeholder="Briefly describe the context — vehicle history, operating conditions, when the issue was first noticed, any prior service actions..."></textarea>
            </div>
          </div>
        </div>

        <!-- SECTION 2: PROBLEM STATEMENT TABLE -->
        <div class="ps-section">
          <div class="sec-heading">Problem Statement</div>
          <div class="form-grid">
            <div class="frow">
              <label class="flabel">Part Name *</label>
              <input class="finput" id="fi-part" placeholder="e.g. HV Battery Pack">
            </div>
            <div class="frow">
              <label class="flabel">Problem Description *</label>
              <input class="finput" id="fi-prob" placeholder="e.g. DTC 4 triggered during charging">
            </div>
            <div class="frow">
              <label class="flabel">Complaint Date *</label>
              <input class="finput" id="fi-date" readonly value="${new Date().toLocaleDateString('en-IN')}">
            </div>
            <div class="frow">
              <label class="flabel">Location / Bay</label>
              <input class="finput" id="fi-loc" placeholder="e.g. BMTC/MTC">
            </div>
            <div class="frow">
              <label class="flabel">Vehicle Number *</label>
              <input class="finput" id="fi-vin" placeholder="e.g. P5FREEUD3SENA1950">
            </div>
            <div class="frow">
              <label class="flabel">ODO Reading (km) *</label>
              <input class="finput" id="fi-odo" type="number" placeholder="e.g. 12450">
            </div>
            <div class="frow">
              <label class="flabel">Operator Name *</label>
              <input class="finput" id="fi-op" placeholder="e.g. Sharon Samuel">
            </div>
            <div class="frow">
              <label class="flabel">Remarks *</label>
              <input class="finput" id="fi-op" placeholder="e.g. Any Remarks if there!">
            </div>
          </div>
        </div>

        <!-- SECTION 3: DTC SELECTION (multi) -->
        <div class="ps-section">
          <div class="sec-heading">DTC Selection</div>
          <div class="form-grid" style="grid-template-columns:1fr">
            <div class="frow">
              <label class="flabel">DTC Code(s) * — select one or more</label>
              <div style="position:relative">
                <input class="finput" id="fi-dtc-search" placeholder="🔍 Search DTC code or name…"
                  oninput="filterDTCOptions(this.value)" autocomplete="off"
                  style="margin-bottom:4px">
              </div>
              <div id="fi-dtc-list" style="
                  max-height:180px;overflow-y:auto;border:1px solid var(--border);
                  border-radius:8px;background:var(--bg2);padding:4px 0;">
                ${Object.values(DTC_LIBRARY)
                    .filter(d => !d.vehicles || d.vehicles.includes(vehicle))
                    .map(d => `
                  <label class="dtc-opt" data-code="${d.code}" data-name="${d.name.toLowerCase()}" style="
                      display:flex;align-items:center;gap:10px;padding:7px 12px;
                      cursor:pointer;transition:background .15s;font-size:.82rem;">
                    <input type="checkbox" value="${d.code}" style="accent-color:var(--primary);width:15px;height:15px;flex-shrink:0">
                    <span><strong>DTC ${d.code}</strong> — ${d.name}</span>
                  </label>`).join('')}
              </div>
              <div id="fi-dtc-tags" style="display:flex;flex-wrap:wrap;gap:6px;margin-top:8px;min-height:24px"></div>
            </div>
          </div>
        </div>

        <button class="btn-start" onclick="startDiag()">Start Diagnostic Procedure →</button>
      </div>
    </div>`;
}

function filterDTCOptions(q) {
  const lq = q.toLowerCase();
  document.querySelectorAll('#fi-dtc-list .dtc-opt').forEach(el => {
    const match = el.dataset.code.includes(lq) || el.dataset.name.includes(lq);
    el.style.display = match ? '' : 'none';
  });
}

/* Keep tags in sync whenever a checkbox changes */
document.addEventListener('change', e => {
  if (e.target.closest('#fi-dtc-list')) syncDTCTags();
});

function syncDTCTags() {
  const tags = document.getElementById('fi-dtc-tags');
  if (!tags) return;
  tags.innerHTML = '';
  document.querySelectorAll('#fi-dtc-list input[type=checkbox]:checked').forEach(cb => {
    const dtc = DTC_LIBRARY[cb.value];
    const t   = document.createElement('span');
    t.style.cssText = 'background:var(--primary);color:#fff;border-radius:20px;padding:3px 10px;font-size:.75rem;display:flex;align-items:center;gap:6px';
    t.innerHTML = `DTC ${dtc.code} <span style="cursor:pointer;opacity:.8" onclick="removeDTCTag('${dtc.code}')">✕</span>`;
    tags.appendChild(t);
  });
}

function removeDTCTag(code) {
  const cb = document.querySelector(`#fi-dtc-list input[value="${code}"]`);
  if (cb) { cb.checked = false; syncDTCTags(); }
}

function startDiag() {
  const intro   = document.getElementById('fi-intro').value.trim();
  const part    = document.getElementById('fi-part').value.trim();
  const prob    = document.getElementById('fi-prob').value.trim();
  const vin     = document.getElementById('fi-vin').value.trim();
  const odo     = document.getElementById('fi-odo').value.trim();
  const op      = document.getElementById('fi-op').value.trim();

  /* Collect all checked DTC codes */
  const checkedCodes = [...document.querySelectorAll('#fi-dtc-list input[type=checkbox]:checked')]
    .map(cb => cb.value);

  if (!intro || !part || !prob || !vin || !op || checkedCodes.length === 0) {
    alert('Please fill all required fields (*) and select at least one DTC code.');
    return;
  }

  /* Build a combined "virtual" DTC from all selected codes */
  const selectedDTCs = checkedCodes.map(c => DTC_LIBRARY[c]).filter(Boolean);
  const combinedCases = selectedDTCs.flatMap(d => d.cases.map(c => ({ ...c, _dtcCode: d.code, _dtcName: d.name })));

  activeDTC = {
    code:        selectedDTCs.map(d => d.code).join(', '),
    name:        selectedDTCs.map(d => d.name).join(' / '),
    description: selectedDTCs.map(d => d.description).join(' | '),
    action:      [...new Set(selectedDTCs.map(d => d.action))].join(' / '),
    severity:    selectedDTCs[0].severity,
    category:    [...new Set(selectedDTCs.map(d => d.category))].join(', '),
    vehicles:    selectedDTCs[0].vehicles,
    cases:       combinedCases,
    _selectedDTCs: selectedDTCs   /* keep originals for export */
  };

  /* Save intake data */
  intake = {
    intro, part, prob,
    date:   document.getElementById('fi-date').value,
    loc:    document.getElementById('fi-loc').value  || '—',
    vin, odo: odo || '—',
    failed: document.getElementById('fi-failed') ? document.getElementById('fi-failed').value : 'To be determined',
    op, vehicle,
    dtcCodes: checkedCodes
  };

  document.getElementById('dOp').textContent = `Operator: ${op} · VIN: ${vin}`;

  currentCase = 0;
  answers     = {};
  buildCaseBar(activeDTC);
  renderCase(0);
}


/* ══════════════════════════════════════════════════════════════════════════
   9. RENDER CASE
   Builds the step cards for a given case index.
══════════════════════════════════════════════════════════════════════════ */

function renderCase(ci) {
  currentCase = ci;
  updateCaseBar(ci);

  const dtc = activeDTC;
  const c   = dtc.cases[ci];

  /* ── Build HTML for each step ── */
  const stepsHtml = c.steps.map((s, si) => {
    const ans      = answers[ci] && answers[ci][si];
    const answered = ans && ans.value != null && ans.value !== '';
    const flagged  = answered && (ans.value === 'NO' || ans.value === 'NOT OK');
    const cardCls  = answered ? (flagged ? 'flagged' : 'answered') : '';
    const notes    = (ans && ans.notes) ? ans.notes : '';

    /* Input widget based on input_type */
    let inputHtml = '';

    if (s.input_type === 'yesno') {
      const ysel = (answered && ans.value === 'YES')    ? 'sel' : '';
      const nsel = (answered && ans.value === 'NO')     ? 'sel' : '';
      inputHtml = `
        <div class="yn-btns">
          <button class="yn-btn yes ${ysel}" onclick="setAns(${ci},${si},'YES',this)">✓ YES</button>
          <button class="yn-btn no  ${nsel}" onclick="setAns(${ci},${si},'NO',this)">✗ NO</button>
        </div>`;

    } else if (s.input_type === 'condition') {
      const c1 = (answered && ans.value === 'OK')     ? 'sel' : '';
      const c2 = (answered && ans.value === 'NOT OK') ? 'sel' : '';
      inputHtml = `
        <div class="cond-btns">
          <button class="cond-btn ${c1}" onclick="setAns(${ci},${si},'OK',this)">✓ OK — Properly Mounted</button>
          <button class="cond-btn ${c2}" onclick="setAns(${ci},${si},'NOT OK',this)">✗ Not OK — Issue Found</button>
        </div>`;

    } else {
      /* number / resistance */
      const unit   = s.obs_label.toLowerCase().includes('resist') ? 'Ω' : '';
      const curVal = (ans && ans.value != null) ? ans.value : '';
      inputHtml = `
        <div class="num-wrap">
          <input class="num-input" type="number" step="any" value="${curVal}"
            placeholder="Enter reading..." id="num-${ci}-${si}"
            oninput="setAns(${ci},${si},this.value,this)">
          <span class="num-unit">${unit}</span>
        </div>`;
    }

    return `
      <div class="step-card ${cardCls}" id="sc-${ci}-${si}">
        <div class="sc-top">
          <div class="sc-num">${String(si + 1).padStart(2, '0')}</div>
          <div class="sc-body">
            <div class="sc-step">${s.step}</div>
            <div class="sc-obs-lbl">${s.obs_label}</div>
            ${inputHtml}
            <div class="sc-corrective ${flagged ? 'show' : ''}" id="corr-${ci}-${si}">⚡ ${s.corrective}</div>
            <div class="sc-ok ${(answered && !flagged) ? 'show' : ''}" id="ok-${ci}-${si}">✓ Observation recorded</div>
            <textarea class="sc-notes" id="notes-${ci}-${si}"
              placeholder="Add notes (optional)..."
              onblur="saveNotes(${ci},${si},this.value)">${notes}</textarea>
          </div>
        </div>
      </div>`;
  }).join('');

  const isLast = ci === dtc.cases.length - 1;

  document.getElementById('diagContent').innerHTML = `
    <div style="padding:18px 0 0;">

      <!-- DTC info banner -->
      <div class="dtc-hdr">
        <span class="dtc-badge">DTC ${dtc.code}</span>
        <div class="dtc-info">
          <div class="dtc-name">${dtc.name}</div>
          <div class="dtc-desc">${dtc.description}</div>
        </div>
        <span class="dtc-act">⚠ ${dtc.action}</span>
      </div>

      <!-- Case steps -->
      <div class="case-panel">
        <div class="cp-hd">
          <span class="cp-badge">Case ${ci + 1} of ${dtc.cases.length}</span>
          <div>
            <div class="cp-area-group">${c.area_group}</div>
            <div class="cp-title">${c.area_detail}</div>
          </div>
          <span class="cp-cnt">${c.steps.length} steps</span>
        </div>
        ${stepsHtml}
      </div>

      <!-- Navigation -->
      <div class="case-nav">
        <button class="btn-case" onclick="navigateCase(${ci - 1})" ${ci === 0 ? 'disabled' : ''}>← Previous</button>
        <div class="nav-info">Case ${ci + 1} of ${dtc.cases.length}</div>
        ${isLast
          ? `<button class="btn-case primary" onclick="finishDiag()">Complete & View Summary ✓</button>`
          : `<button class="btn-case primary" onclick="navigateCase(${ci + 1})">Next Case →</button>`
        }
      </div>

      <!-- Export bar -->
      <div class="export-bar">
        <div class="xwrap">
          <button class="btn-exp" onclick="toggleExport()">⬇ Export Report</button>
          <div class="xmenu" id="xmenu">
            <div class="xitem" onclick="doExport('pdf')"><span>📄</span>Download PDF</div>
            <div class="xitem" onclick="doExport('word')"><span>📝</span>Download Word</div>
          </div>
        </div>
        <button class="btn-rst" onclick="showProblemStatement()">↺ New Session</button>
        <div class="exp-status">Session: ${SESS}</div>
      </div>

    </div>`;

  document.getElementById('diagContent').scrollTop = 0;
}


/* ══════════════════════════════════════════════════════════════════════════
   10. ANSWER LOGIC
══════════════════════════════════════════════════════════════════════════ */

function setAns(ci, si, val, el) {
  if (!answers[ci]) answers[ci] = {};

  /* Preserve existing notes */
  const notesEl  = document.getElementById(`notes-${ci}-${si}`);
  const curNotes = notesEl ? notesEl.value : '';
  answers[ci][si] = { value: val, notes: curNotes };

  const card    = document.getElementById(`sc-${ci}-${si}`);
  const flagged = val === 'NO' || val === 'NOT OK';
  const answered = val != null && val !== '';

  /* Deselect all buttons in this card, select clicked one */
  if (el && el.tagName === 'BUTTON') {
    card.querySelectorAll('.yn-btn, .cond-btn').forEach(b => b.classList.remove('sel'));
    el.classList.add('sel');
  }

  card.className = 'step-card ' + (answered ? (flagged ? 'flagged' : 'answered') : '');

  /* Show/hide corrective action and ok message */
  const corr = document.getElementById(`corr-${ci}-${si}`);
  const ok   = document.getElementById(`ok-${ci}-${si}`);
  if (corr) corr.className = 'sc-corrective' + (flagged ? ' show' : '');
  if (ok)   ok.className   = 'sc-ok'          + (answered && !flagged ? ' show' : '');
}

function saveNotes(ci, si, val) {
  if (!answers[ci])       answers[ci]    = {};
  if (!answers[ci][si])   answers[ci][si] = { value: null };
  answers[ci][si].notes = val;
}


/* ══════════════════════════════════════════════════════════════════════════
   11. CASE NAVIGATION
══════════════════════════════════════════════════════════════════════════ */

function navigateCase(idx) {
  if (!activeDTC || idx < 0 || idx >= activeDTC.cases.length) return;
  renderCase(idx);
}


/* ══════════════════════════════════════════════════════════════════════════
   12. FINISH / SUMMARY
══════════════════════════════════════════════════════════════════════════ */

function finishDiag() {
  const dtc = activeDTC;
  updateCaseBar(dtc.cases.length);
  document.getElementById('d-prog').textContent = 'Complete';

  let flagCount = 0;

  /* Build per-case observation tables */
  let tableHtml = '';

  dtc.cases.forEach((c, ci) => {
    let rows = '';
    c.steps.forEach((s, si) => {
      const ans  = answers[ci] && answers[ci][si];
      const val  = (ans && ans.value != null && ans.value !== '') ? String(ans.value) : '—';
      const notes = (ans && ans.notes) ? ans.notes : '';
      const flag  = val === 'NO' || val === 'NOT OK';
      if (flag) flagCount++;

      const vc = flag ? 'v-no'
               : (val === 'YES' || val === 'OK') ? 'v-yes'
               : (val === '—') ? 'v-none'
               : (!isNaN(Number(val)) ? 'v-num' : 'v-ok');

      rows += `
        <tr class="${flag ? 'flag-row' : ''}">
          <td style="color:var(--text3);font-family:var(--mono);font-size:.7rem;width:28px">${String(si + 1).padStart(2, '0')}</td>
          <td style="font-size:.79rem;color:var(--text);line-height:1.4">${s.step}</td>
          <td><span class="${vc}" style="font-size:.78rem">${val}</span></td>
          <td style="font-size:.72rem;color:var(--text3)">${notes}</td>
          ${flag
            ? `<td style="font-size:.72rem;color:var(--amber);font-style:italic">${s.corrective}</td>`
            : `<td style="font-size:.72rem;color:var(--green)">✓</td>`}
        </tr>`;
    });

    tableHtml += `
      <div class="otw-section">
        <div class="otw-sec-title">
          ${c.area_group} — ${c.area_detail}
          <span style="margin-left:auto;font-weight:400">${c.steps.length} steps</span>
        </div>
        <table class="obs-tbl">
          <thead>
            <tr>
              <th>#</th>
              <th>Diagnostic Step</th>
              <th>Observation</th>
              <th>Notes</th>
              <th>Action Required</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>
      </div>`;
  });

  document.getElementById('diagContent').innerHTML = `
    <div style="padding:18px 0 0;">

      <div class="complete-card">
        <div class="cc-icon">✅</div>
        <div class="cc-title">Diagnosis Complete — DTC ${dtc.code}</div>
        <div class="cc-sub">
          All ${dtc.cases.length} cases checked · VIN: ${intake.vin}
          · ${flagCount > 0 ? flagCount + ' item(s) flagged for action' : 'All checks passed'}
        </div>
        <div class="cc-btns">
          <button class="cc-btn" onclick="doExport('pdf')">📄 Download PDF Report</button>
          <button class="cc-btn" onclick="doExport('word')">📝 Download Word Report</button>
          <button class="cc-btn" onclick="showProblemStatement()">↺ New Session</button>
        </div>
      </div>

      <div class="obs-table-wrap">
        <div class="otw-head">
          <span>Key Observations & Insights — DTC ${dtc.code} · ${dtc.name}</span>
          <span style="font-family:var(--mono);font-size:.65rem;color:${flagCount > 0 ? 'var(--amber)' : 'var(--green)'}">
            ${flagCount > 0 ? `⚠ ${flagCount} flagged` : '✓ All clear'}
          </span>
        </div>
        ${tableHtml}
      </div>

      <!-- ── Diagnostic Remarks & Key Inputs ── -->
      <div class="obs-table-wrap" style="margin-top:18px;">
        <div class="otw-head">
          <span>📝 Diagnostic Remarks &amp; Key Inputs</span>
          <span style="font-family:var(--mono);font-size:.65rem;color:var(--text3)">Saved with report export</span>
        </div>
        <div style="padding:16px 18px;display:flex;flex-direction:column;gap:14px;">
          <div class="frow">
            <label class="flabel" style="font-size:.78rem;font-weight:600;margin-bottom:4px;">Diagnostic Remarks</label>
            <textarea id="diag-remarks" class="sc-notes" rows="4"
              placeholder="Summarise the diagnostic findings, root cause identified, parts replaced, actions taken…"
              style="width:100%;min-height:90px;resize:vertical;border-radius:8px;padding:10px;font-size:.83rem;box-sizing:border-box;"
              onblur="saveRemarks()">${intake.diagRemarks||''}</textarea>
          </div>
          <div class="frow">
            <label class="flabel" style="font-size:.78rem;font-weight:600;margin-bottom:4px;">Key Inputs / Findings</label>
            <textarea id="diag-keyinputs" class="sc-notes" rows="3"
              placeholder="List key measurements, sensor readings, wire numbers checked, or any critical data points noted…"
              style="width:100%;min-height:70px;resize:vertical;border-radius:8px;padding:10px;font-size:.83rem;box-sizing:border-box;"
              onblur="saveKeyInputs()">${intake.diagKeyInputs||''}</textarea>
          </div>
        </div>
      </div>

      <div class="export-bar" style="padding-bottom:20px;">
        <div class="xwrap">
          <button class="btn-exp" onclick="toggleExport()">⬇ Export Report</button>
          <div class="xmenu" id="xmenu">
            <div class="xitem" onclick="doExport('pdf')"><span>📄</span>Download PDF</div>
            <div class="xitem" onclick="doExport('word')"><span>📝</span>Download Word</div>
          </div>
        </div>
        <button class="btn-rst" onclick="showProblemStatement()">↺ New Session</button>
        <div class="exp-status">Session: ${SESS}</div>
      </div>
    </div>`;
}

function saveRemarks() {
  const el = document.getElementById('diag-remarks');
  if (el) intake.diagRemarks = el.value;
}

function saveKeyInputs() {
  const el = document.getElementById('diag-keyinputs');
  if (el) intake.diagKeyInputs = el.value;
}


/* ══════════════════════════════════════════════════════════════════════════
   13. EXPORT (PDF + Word)
   Reports follow the template structure:
     1. Problem Discription
     2. Problem Statement (table)
     3. Root Cause Analysis
     4. Key Observations & Insights (observations table)
══════════════════════════════════════════════════════════════════════════ */

function toggleExport() {
  document.getElementById('xmenu').classList.toggle('open');
}

document.addEventListener('click', e => {
  if (!e.target.closest('.xwrap')) document.getElementById('xmenu')?.classList.remove('open');
});

function doExport(type) {
  document.getElementById('xmenu')?.classList.remove('open');
  if (!activeDTC || !intake.op) { alert('Complete the intake form first.'); return; }
  /* Grab latest remarks/key-inputs in case user didn't blur */
  const rEl = document.getElementById('diag-remarks');
  const kEl = document.getElementById('diag-keyinputs');
  if (rEl) intake.diagRemarks   = rEl.value;
  if (kEl) intake.diagKeyInputs = kEl.value;
  const d = {
    session: SESS,
    generated: new Date().toLocaleString('en-IN'),
    ...intake,
    dtc: activeDTC,
    answers
  };
  type === 'pdf' ? exportPDF(d) : exportWord(d);
}

/* ── PDF Export ── */
function exportPDF(d) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210, M = 18;
  let y = 0;

  const addPage = () => { doc.addPage(); y = 20; };
  const checkY  = need => { if (y + need > 272) addPage(); };

  /* ─ Cover header ─ */
  doc.setFillColor(72,69,210); doc.rect(0,0,W,32,'F');
  doc.setFillColor(255,255,255); doc.rect(0,32,W,4,'F');
  doc.setFont('helvetica','bold'); doc.setFontSize(20); doc.setTextColor(255,255,255);
  doc.text('SWITCH', M, 14);
  doc.setFont('helvetica','normal'); doc.setFontSize(9);
  doc.text('Diagnostic Tool · Current Engineering', M, 22);
  doc.text(`Session: ${d.session}  |  ${d.generated}`, W-M, 14, { align: 'right' });
  doc.text(`Vehicle: ${d.vehicle}  |  VIN: ${d.vin}`,  W-M, 22, { align: 'right' });
  y = 48;

  /* ─ Helpers ─ */
  const sh = (t, yy, col=[72,69,210]) => {
    doc.setFillColor(244,246,251); doc.rect(M, yy-5, W-M*2, 8, 'F');
    doc.setFillColor(...col); doc.rect(M, yy-5, 3, 8, 'F');
    doc.setFont('helvetica','bold'); doc.setFontSize(7.5); doc.setTextColor(82,88,120);
    doc.text(t, M+6, yy);
    return yy + 10;
  };

  const trow = (lbl, val, yy) => {
    doc.setFillColor(244,246,251); doc.rect(M, yy-4, W-M*2, 8, 'F');
    doc.setFont('helvetica','bold'); doc.setFontSize(8); doc.setTextColor(82,88,120);
    doc.text(lbl, M+2, yy);
    doc.setFont('helvetica','normal'); doc.setFontSize(8.5); doc.setTextColor(26,29,46);
    const vl = doc.splitTextToSize(String(val||'—'), W-M*2-46);
    doc.text(vl[0]||'', M+46, yy);
    return yy + 8;
  };

  /* ─ 1. Problem Discription ─ */
  doc.setFont('helvetica','bold'); doc.setFontSize(13); doc.setTextColor(26,29,46);
  doc.text('1. Problem Discription', M, y); y += 8;
  doc.setFont('helvetica','normal'); doc.setFontSize(9.5); doc.setTextColor(82,88,120);
  const introLines = doc.splitTextToSize(d.intro || '—', W-M*2);
  doc.text(introLines, M, y);
  y += introLines.length * 5.5 + 6;
  doc.setFillColor(226,230,239); doc.rect(M, y, W-M*2, .5, 'F'); y += 6;

  /* ─ 2. Problem Statement ─ */
  checkY(50);
  doc.setFont('helvetica','bold'); doc.setFontSize(13); doc.setTextColor(26,29,46);
  doc.text('2. PROBLEM STATEMENT', M, y); y += 8;

  /* Blue table header */
  doc.setFillColor(72,69,210); doc.rect(M, y-5, W-M*2, 8, 'F');
  doc.setFont('helvetica','bold'); doc.setFontSize(7); doc.setTextColor(255,255,255);
  doc.text('FIELD', M+2, y); doc.text('VALUE', M+48, y); y += 5;

  y = trow('Part Name',                  d.part,                         y);
  y = trow('Problem Description',        d.prob,                         y);
  y = trow('Complaint Date',             d.date,                         y);
  y = trow('Location',                   d.loc,                          y);
  y = trow('Vehicle Number',             d.vin,                           y);
   y = trow('ODO',                       d.odo,                          y);
  y = trow('Failed Part',                d.failed,                        y);
  y = trow('Operator',                   d.op,                           y);
  y = trow('DTC Code(s)',                `DTC ${d.dtc.code} — ${d.dtc.name}`, y);
  y += 6;
  doc.setFillColor(226,230,239); doc.rect(M, y, W-M*2, .5, 'F'); y += 6;

  /* ─ 3. Root Cause Analysis ─ */
  checkY(20);
  doc.setFont('helvetica','bold'); doc.setFontSize(13); doc.setTextColor(26,29,46);
  doc.text('3. ROOT CAUSE ANALYSIS', M, y); y += 8;
  doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(82,88,120);
  doc.text(`DTC ${d.dtc.code} (${d.dtc.name}) triggered. Action: ${d.dtc.action}.`, M, y); y += 6;
  doc.text(`Diagnostic performed across all ${d.dtc.cases.length} cases. See observations below.`, M, y); y += 10;
  doc.setFillColor(226,230,239); doc.rect(M, y, W-M*2, .5, 'F'); y += 6;

  /* ─ 4. Key Observations ─ */
  checkY(20);
  doc.setFont('helvetica','bold'); doc.setFontSize(13); doc.setTextColor(26,29,46);
  doc.text('4. KEY OBSERVATIONS & INSIGHTS', M, y); y += 10;

  d.dtc.cases.forEach((c, ci) => {
    checkY(20);
    y = sh(`CASE ${ci+1}: ${c.area_group.toUpperCase()} — ${c.area_detail.toUpperCase()}`, y);

    /* Column headers */
    doc.setFillColor(240,242,252); doc.rect(M, y-4, W-M*2, 7, 'F');
    doc.setFont('helvetica','bold'); doc.setFontSize(6.5); doc.setTextColor(82,88,120);
    doc.text('#', M+1, y); doc.text('STEP', M+8, y); doc.text('OBS', M+122, y); doc.text('NOTES / CORRECTIVE', M+144, y);
    y += 7;

    c.steps.forEach((s, si) => {
      checkY(10);
      const ans   = d.answers[ci] && d.answers[ci][si];
      const val   = (ans && ans.value != null && ans.value !== '') ? String(ans.value) : '—';
      const notes = (ans && ans.notes) ? ans.notes : '';
      const flag  = val === 'NO' || val === 'NOT OK';
      const bg    = flag ? [255,248,237] : (val !== '—' ? [240,253,244] : [250,251,254]);

      doc.setFillColor(...bg); doc.rect(M, y-4, W-M*2, 8, 'F');
      doc.setFont('helvetica','bold'); doc.setFontSize(7); doc.setTextColor(72,69,210);
      doc.text(String(si+1).padStart(2,'0'), M+1, y);

      doc.setFont('helvetica','normal'); doc.setFontSize(7.5); doc.setTextColor(26,29,46);
      const sl = doc.splitTextToSize(s.step, 108);
      doc.text(sl[0]||'', M+8, y);

      const vc = flag ? [220,38,38] : (val !== '—' ? [22,163,74] : [155,160,190]);
      doc.setFont('helvetica','bold'); doc.setTextColor(...vc);
      doc.text(val, M+122, y);

      if (flag) {
        doc.setFont('helvetica','italic'); doc.setFontSize(6.5); doc.setTextColor(217,119,6);
        const ca = doc.splitTextToSize(s.corrective, 54);
        doc.text(ca[0]||'', M+144, y);
      } else if (notes) {
        doc.setFont('helvetica','normal'); doc.setFontSize(6.5); doc.setTextColor(82,88,120);
        doc.text(notes.substring(0,40), M+144, y);
      }
      y += 8;
    });
    y += 4;
  });

  /* ─ 5. Diagnostic Remarks & Key Inputs ─ */
  if (d.diagRemarks || d.diagKeyInputs) {
    checkY(20);
    doc.setFillColor(226,230,239); doc.rect(M, y, W-M*2, .5, 'F'); y += 6;
    doc.setFont('helvetica','bold'); doc.setFontSize(13); doc.setTextColor(26,29,46);
    doc.text('5. DIAGNOSTIC REMARKS & KEY INPUTS', M, y); y += 8;

    if (d.diagRemarks) {
      doc.setFont('helvetica','bold'); doc.setFontSize(9); doc.setTextColor(72,69,210);
      doc.text('Diagnostic Remarks:', M, y); y += 6;
      doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(82,88,120);
      const rl = doc.splitTextToSize(d.diagRemarks, W-M*2);
      rl.forEach(line => { checkY(7); doc.text(line, M, y); y += 5.5; });
      y += 4;
    }

    if (d.diagKeyInputs) {
      checkY(14);
      doc.setFont('helvetica','bold'); doc.setFontSize(9); doc.setTextColor(72,69,210);
      doc.text('Key Inputs / Findings:', M, y); y += 6;
      doc.setFont('helvetica','normal'); doc.setFontSize(9); doc.setTextColor(82,88,120);
      const kl = doc.splitTextToSize(d.diagKeyInputs, W-M*2);
      kl.forEach(line => { checkY(7); doc.text(line, M, y); y += 5.5; });
      y += 4;
    }
  }

  /* Footer */
  const FY = doc.internal.pageSize.height;
  doc.setFillColor(244,246,251); doc.rect(0, FY-16, W, 16, 'F');
  doc.setFont('helvetica','normal'); doc.setFontSize(7); doc.setTextColor(155,163,190);
  doc.text('SWITCH Diagnostic Tool · Current Engineering · Confidential', M, FY-8);
  doc.text(`${d.generated} · Session ${d.session}`, W-M, FY-8, { align: 'right' });

  doc.save(`DTC${d.dtc.code.replace(/[^a-zA-Z0-9]/g,'-')}_${(d.vin||'report').replace(/[^a-zA-Z0-9]/g,'-')}_${d.vehicle}.pdf`);
}

/* ── Word Export ── */
async function exportWord(d) {
  try {
    const { Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
            WidthType, BorderStyle, HeadingLevel, ShadingType } = docx;

    const bdr    = { style: BorderStyle.SINGLE, size: 1, color: 'CBD1E5' };
    const bdrAll = { top: bdr, bottom: bdr, left: bdr, right: bdr };
    const hdrShd = { fill: '4845D2', type: ShadingType.CLEAR };

    const cell = (txt, w, bold, shade, color) => new TableCell({
      width: { size: w, type: WidthType.DXA }, borders: bdrAll,
      shading: shade || { type: ShadingType.CLEAR },
      margins: { top: 80, bottom: 80, left: 120, right: 120 },
      children: [new Paragraph({ children: [new TextRun({ text: txt, bold: bold||false, font: 'Arial', size: 18, color: color||'1A1D35' })] })]
    });
    const hcell = (txt, w) => cell(txt, w, true, hdrShd, 'FFFFFF');

    const children = [];

    /* Title */
    children.push(new Paragraph({ children: [
      new TextRun({ text: 'SWITCH — DIAGNOSTIC REPORT', bold: true, size: 32, color: '4845D2', font: 'Arial' })
    ]}));
    children.push(new Paragraph({ children: [
      new TextRun({ text: `Session: ${d.session}  |  ${d.generated}  |  Vehicle: ${d.vehicle}`, size: 16, color: '9AA0BE', font: 'Courier New' })
    ], spacing: { after: 300 }}));

    /* 1. Problem Discription */
    children.push(new Paragraph({ text: '1. Problem Discription', heading: HeadingLevel.HEADING_1, spacing: { after: 120 } }));
    children.push(new Paragraph({ children: [new TextRun({ text: d.intro||'—', size: 20, font: 'Arial' })], spacing: { after: 300 } }));

    /* 2. Problem Statement */
    children.push(new Paragraph({ text: '2. PROBLEM STATEMENT', heading: HeadingLevel.HEADING_1, spacing: { after: 120 } }));
    const psRows = [
      ['Part Name',                d.part],
      ['Problem Description',      d.prob],
      ['Complaint Date & Location', `${d.date} / ${d.loc}`],
      ['Vehicle Number & ODO',     `${d.vin} / ${d.odo} km`],
      ['Failed Part',              d.failed],
      ['Operator',                 d.op],
      ['DTC Code(s)',                `DTC ${d.dtc.code} — ${d.dtc.name}`]
    ];
    children.push(new Table({
      width: { size: 9360, type: WidthType.DXA }, columnWidths: [2800, 6560],
      rows: [
        new TableRow({ children: [hcell('Field', 2800), hcell('Value', 6560)] }),
        ...psRows.map(([l, v]) => new TableRow({ children: [cell(l, 2800, true), cell(v, 6560)] }))
      ]
    }));
    children.push(new Paragraph({ spacing: { after: 300 }, children: [new TextRun({ text: '', size: 4 })] }));

    /* 3. Root Cause Analysis */
    children.push(new Paragraph({ text: '3. ROOT CAUSE ANALYSIS', heading: HeadingLevel.HEADING_1, spacing: { after: 120 } }));
    children.push(new Paragraph({ children: [
      new TextRun({ text: `DTC ${d.dtc.code} (${d.dtc.name}) triggered on ${d.vehicle} unit ${d.vin}. Immediate action: ${d.dtc.action}. Full diagnostic performed across all ${d.dtc.cases.length} cases.`, size: 20, font: 'Arial' })
    ], spacing: { after: 300 } }));

    /* 4. Key Observations */
    children.push(new Paragraph({ text: '4. KEY OBSERVATIONS & INSIGHTS', heading: HeadingLevel.HEADING_1, spacing: { after: 120 } }));

    d.dtc.cases.forEach((c, ci) => {
      children.push(new Paragraph({ children: [
        new TextRun({ text: `Case ${ci+1}: ${c.area_group} — ${c.area_detail}`, bold: true, size: 20, color: '4845D2', font: 'Arial' })
      ], spacing: { before: 200, after: 80 } }));

      children.push(new Table({
        width: { size: 9360, type: WidthType.DXA },
        columnWidths: [360, 4600, 1200, 1400, 1800],
        rows: [
          new TableRow({ children: [hcell('#', 360), hcell('Diagnostic Step', 4600), hcell('Observation', 1200), hcell('Notes', 1400), hcell('Corrective Action', 1800)] }),
          ...c.steps.map((s, si) => {
            const ans   = d.answers[ci] && d.answers[ci][si];
            const val   = (ans && ans.value != null && ans.value !== '') ? String(ans.value) : '—';
            const notes = (ans && ans.notes) ? ans.notes : '';
            const flag  = val === 'NO' || val === 'NOT OK';
            const vcolor = flag ? 'DC2626' : (val !== '—' ? '16A34A' : '9AA0BE');
            const rowShd = flag ? { fill: 'FFF8ED', type: ShadingType.CLEAR } : { type: ShadingType.CLEAR };
            return new TableRow({ children: [
              cell(String(si+1), 360, false, rowShd),
              cell(s.step,       4600, false, rowShd),
              new TableCell({
                width: { size: 1200, type: WidthType.DXA }, borders: bdrAll, shading: rowShd,
                margins: { top: 80, bottom: 80, left: 120, right: 120 },
                children: [new Paragraph({ children: [new TextRun({ text: val, bold: true, color: vcolor, font: 'Courier New', size: 17 })] })]
              }),
              cell(notes,                          1400, false, rowShd),
              cell(flag ? s.corrective : '✓',      1800, flag,  rowShd, flag ? 'D97706' : '16A34A')
            ]});
          })
        ]
      }));
      children.push(new Paragraph({ spacing: { after: 200 }, children: [new TextRun({ text: '', size: 4 })] }));
    });

    /* 5. Diagnostic Remarks & Key Inputs */
    if (d.diagRemarks || d.diagKeyInputs) {
      children.push(new Paragraph({ text: '5. DIAGNOSTIC REMARKS & KEY INPUTS', heading: HeadingLevel.HEADING_1, spacing: { after: 120 } }));
      if (d.diagRemarks) {
        children.push(new Paragraph({ children: [new TextRun({ text: 'Diagnostic Remarks', bold: true, size: 20, color: '4845D2', font: 'Arial' })], spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: d.diagRemarks, size: 20, font: 'Arial' })], spacing: { after: 200 } }));
      }
      if (d.diagKeyInputs) {
        children.push(new Paragraph({ children: [new TextRun({ text: 'Key Inputs / Findings', bold: true, size: 20, color: '4845D2', font: 'Arial' })], spacing: { after: 60 } }));
        children.push(new Paragraph({ children: [new TextRun({ text: d.diagKeyInputs, size: 20, font: 'Arial' })], spacing: { after: 200 } }));
      }
    }

    const dc  = new Document({ styles: { default: { document: { run: { font: 'Arial', size: 20 } } } }, sections: [{ children }] });
    const buf = await Packer.toBlob(dc);
    saveAs(buf, `DTC${d.dtc.code.replace(/[^a-zA-Z0-9]/g,'-')}_${(d.vin||'rpt').replace(/[^a-zA-Z0-9]/g,'-')}_${d.vehicle}.docx`);

  } catch (e) {
    console.error(e);
    alert('Word export failed — try PDF instead.');
  }
}


/* ══════════════════════════════════════════════════════════════════════════
   14. PAGE NAVIGATION
══════════════════════════════════════════════════════════════════════════ */

function showPage(id, btn) {
  document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
  document.querySelectorAll('.ntab').forEach(b => b.classList.remove('active'));
  document.getElementById('pg-' + id).classList.add('active');
  btn.classList.add('active');
}


/* ══════════════════════════════════════════════════════════════════════════
   15. NEWSLETTER
══════════════════════════════════════════════════════════════════════════ */

function buildNL() {
  const grid = document.getElementById('nlGrid');
  NL_DATA.slice(1).forEach((n, i) => {
    const c = document.createElement('div');
    c.className = 'ic';
    c.innerHTML = `
      <div class="ic-top">
        <div class="ic-row">
          <div class="ic-num">Issue #${n.id} · ${n.date} · ${n.readTime}</div>
          ${n.isNew ? '<div class="ic-new">NEW</div>' : ''}
        </div>
        <div class="ic-title">${n.title}</div>
      </div>
      <div class="ic-body">
        <p class="ic-desc">${n.excerpt}</p>
        <div class="tags">${n.tags.map((t,j) => `<span class="tag ${n.tagColors[j]||''}">${t}</span>`).join('')}</div>
      </div>`;
    c.onclick = () => openReader(i + 1);
    grid.appendChild(c);
  });
}

function openReader(idx) {
  const n = NL_DATA[idx];
  if (!n) return;
  document.getElementById('rdMeta').textContent = `Issue #${n.id} · ${n.date} · ${n.readTime}`;
  document.getElementById('rdContent').innerHTML = `
    <div class="rd-tag">${n.tags.join(' · ')}</div>
    <div class="rd-title">${n.title}</div>
    <div class="rd-meta"><span>#${n.id}</span><span>${n.date}</span><span>${n.readTime}</span></div>
    <div class="rd-line"></div>
    ${n.sections.map(s => `
      <div class="rd-sec">
        <div class="rd-h2">${s.heading}</div>
        <div class="rd-body">${s.body.replace(/\n/g, '<br>')}</div>
      </div>`).join('')}`;
  const rd = document.getElementById('nlReader');
  rd.classList.add('open');
  rd.scrollTop = 0;
}

function closeReader() {
  document.getElementById('nlReader').classList.remove('open');
}

function nlSub(id) {
  const v = document.getElementById(id).value.trim();
  if (!v || !v.includes('@')) { alert('Please enter a valid email.'); return; }
  document.getElementById(id).value = '';
  const t = document.getElementById('toast');
  t.classList.add('show');
  setTimeout(() => t.classList.remove('show'), 3500);
}

/* Initialise newsletter grid on page load */
buildNL();
